#pragma once

#define LOG_ALLWAYS WINEVENT_LEVEL_LOG_ALWAYS 
#define LOG_CRIT WINEVENT_LEVEL_CRITICAL 
#define LOG_ERR WINEVENT_LEVEL_ERROR
#define LOG_WARNING WINEVENT_LEVEL_WARNING 
#define LOG_INFO WINEVENT_LEVEL_INFO
#define LOG_VERB WINEVENT_LEVEL_VERBOSE